version: '3.1'
services:
  web:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - database
    tty: true
    stdin_open: true

  database:
    image: postgres:9.6.1
    ports:
      - '5433:5432'
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
